version: '3.8'

services:
  maya:
    build: .
    container_name: maya-chatbot
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/xdg
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/root/.Xauthority
      - ./resources:/home/maya/app/resources
      - maya-config:/home/maya/.config/maya
      - maya-data:/home/maya/.local/share/maya
    devices:
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri
    ipc: host
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true

volumes:
  maya-config:
  maya-data:
